### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by martinthomson** [qpackers/qifs#1]
As long as we require that header blocks are output in the order they appear, I don't see why we need a sorting utility.

**Comment by dtikhonov** [comment]
You could require that: have decoder drivers add dozens of lines of code to buffer and sort the header lists. Or you could sort the output with 5 lines of Perl code.

**Comment by martinthomson** [comment]
So I'm running my decoder in series.  What comes in determines what comes out.  At least for the interop testing.  That is, the input contains an ordered sequence of header blocks and the output is in the same order.

**Comment by dtikhonov** [comment]
Closing -- there is no action to be taken.
