### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xyproto** [qpackers/qifs#7]
Hi,

Could you please add a license file?

Best regards,
Alexander F. Rødseth

**Comment by dtikhonov** [comment]
What for?

**Comment by xyproto** [comment]
The main reason is that in lack of a license, one must assume that the entire project is copyrighted, since that is the default for most countries in the world.

The other is to know if the license, if it's an open source license, is compatible with compiling a project that depends on this one as a statically compiled executable.

**Comment by dtikhonov** [comment]
It's not really a project, just a bunch of files.  There is nothing to compile.  Help yourself to the Perl programs.  QIF encodings have been submitted by many people and are likely in the public domain.

Just take the files, what's the problem?

**Comment by xyproto** [comment]
The "license problem analyzer" site FOSSA believes that my project Algernon depends on 1 project without a license, in a way that is supposedly problematic:

https://app.fossa.com/projects/git%2Bgithub.com%2Fxyproto%2Falgernon?ref=badge_shield

However, looking into this I can't see that any of the projects that [Algernon](https://github.com/xyproto/algernon) depends on in turn depends on your project.

Maybe FOSSA is just wrong.

Never mind then, and sorry for the noise.

**Comment by adam-hanna** [comment]
https://choosealicense.com/no-permission/

> Unless you include a license ... nobody else can copy, distribute, or modify your work... **Once the work has other contributors (each a copyright holder), “nobody” starts including you.**

Emphasis mine.

Having this same issue as well. Many corporations have strict opensource licensing requirements. Without proper licensing, this code will likely be rejected from inclusion in many corporate projects.

I've used [lice](https://github.com/superkhau/lice) before to generate license files. It's quite nice and easy to use.

**Comment by MerlinMason** [comment]
+1 for this please! 

Our current dependency trace from Fossa says we're using this project (via a several layer deep dependency tree) and the default position without a license is this is copyright infringement 😬 

![image](https://user-images.githubusercontent.com/3215478/67403568-07771180-f5aa-11e9-932a-e5898a02ee4a.png)
